Adaptive sampling
Photon-AI-Research/NeuralSolvers pull request #57
Opened 2022-03-23 21:42 UTC by Jeyhun1

Added adaptive sampling to the framework and applied it in 1D Heat Equation and 1D Burgers Equation examples

2022-05-11 14:38 UTC, StillerPatrick commented on PINNFramework/PDELoss.py
> +class PDELossAdaptive(PDELoss):
Why do we need an additional loss term? That's make the framework too complicated. We need a flexible implementation of PDE loss, which can handle multiple sampler

2022-05-11 14:41 UTC, StillerPatrick commented
My remarks:
- schrödinger equation is not in geometry fashion
- PDE loss should allocate the next points from the sampler 
- adaptive PDE loss is ok
- Geometry should be a module such that I have PINNFramework.Geometry
- Geometry should be changed to an interface such that we can implement  multiple ones it
- Geometry should have sampler insight
- Sampler should be a module such that I have PINNFramework.Sampler
- we need some standard samplers such as lhs, random etc. 
- sampler should be implemented from an interface that allows implementing own sampling methods in the future.

2022-07-27 06:50 UTC, StillerPatrick commented on PINNFramework/Geometry.py
> +            sampler (string): sampling method: "random" (pseudorandom), "LHS" (Latin hypercube sampling), and "adaptive" method.
Please split in two lines.

2022-07-27 06:53 UTC, StillerPatrick commented
@sutariyaraj please review the code as well to check if it fits your current implementation of the inference pipeline. Please communicate prober changes.

2022-07-29 08:29 UTC, nih23 requested changes

2022-07-29 08:29 UTC, nih23 commented on PINNFramework/Sampler.py
> +seed = 42
hard coded magic number

2022-07-29 08:29 UTC, nih23 commented on PINNFramework/Sampler.py
> +def sample(lb, ub, num_points, sampler, num_seed, model, pde, device = torch.device("cuda:0")):
the definition of this function is polluted and has to be cleaned because you are asking for parameters that some samples like quasirandym are not using. I suggest to go for an object-oriented rewrite of the full sampling approach.

2022-07-29 08:29 UTC, nih23 commented on PINNFramework/Sampler.py
> +    xf = np.random.uniform(lb,ub,size=(num_points, dimension))
use torch.distribution instead of np.random to avoid unnecessary IO between host (numpy) and device (torch)

2022-07-29 08:29 UTC, nih23 commented on PINNFramework/Sampler.py
> +    print('xf ', (xf))
polluted output

2022-07-29 08:30 UTC, nih23 commented on PINNFramework/Sampler.py
> +    print('xf ', (xf))
the print statements from line 113 result in unnecessary verbose output

2022-07-29 08:32 UTC, StillerPatrick commented on PINNFramework/Sampler.py
> +def sample(lb, ub, num_points, sampler, num_seed, model, pde, device = torch.device("cuda:0")):
I agree. I think we should go back to the OOP Version of the Sampler (sorry for that). This would make the code better to understand and maintainable.

2022-07-29 08:34 UTC, StillerPatrick commented on PINNFramework/Sampler.py
> +def sample(lb, ub, num_points, sampler, num_seed, model, pde, device = torch.device("cuda:0")):
I also miss a definition of the total points we want to sample. This determines the number of iterations we go through the dataset.

2022-07-29 08:34 UTC, StillerPatrick commented on PINNFramework/Sampler.py
> +    xf = np.random.uniform(lb,ub,size=(num_points, dimension))
We definitely check this option as possible performance improvement

2022-07-29 10:06 UTC, Jeyhun1 commented on PINNFramework/Sampler.py
> +    print('xf ', (xf))
Those print statements are deleted in later commits

2022-11-07 12:42 UTC, StillerPatrick commented
Approved. Nice work

2022-11-07 12:42 UTC, merged